# Generated by Django 4.2.1 on 2023-06-26 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diagnosis", "0002_patients_delete_patient"),
    ]

    operations = [
        migrations.AddField(
            model_name="cancertype",
            name="treatments",
            field=models.ManyToManyField(to="diagnosis.treatment"),
        ),
    ]
