# Generated by Django 4.2.1 on 2023-07-01 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diagnosis", "0004_cancertype_symptoms"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cancertype",
            options={"ordering": ["id"]},
        ),
        migrations.AlterField(
            model_name="cancertype",
            name="symptoms",
            field=models.ManyToManyField(
                related_name="symptoms", to="diagnosis.symptom"
            ),
        ),
    ]
