# Generated by Django 4.2.1 on 2023-07-01 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diagnosis", "0007_alter_testresult_patient"),
    ]

    operations = [
        migrations.AddField(
            model_name="testresult",
            name="accuracy",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="testresult",
            name="symptoms",
            field=models.ManyToManyField(to="diagnosis.symptom"),
        ),
    ]
