# Generated by Django 4.2.1 on 2023-07-05 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("diagnosis", "0008_testresult_accuracy_testresult_symptoms"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="symptom",
            options={"ordering": ["-id"]},
        ),
        migrations.AlterModelOptions(
            name="testresult",
            options={"ordering": ["-saved_at"]},
        ),
    ]
