# Generated by Django 4.2.1 on 2023-07-12 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diagnosis", "0010_patientdiagnosis"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientdiagnosis",
            name="recommendation",
            field=models.TextField(null=True),
        ),
    ]
