# Generated by Django 4.2.1 on 2023-07-12 10:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("diagnosis", "0011_patientdiagnosis_recommendation"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientdiagnosis",
            name="date_created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
